<div id="overlay" style="width: 100%; height:100%; position:fixed; background:#000; opacity:.6;z-index:1000;display:none"></div>
<div id="wholesale-box" class="user-forms" style="width:450px;height:480px;z-index:1001;display:none">
		<div class="user-login">
	    	<h1>Retailer &amp; Wholesaler</h1>
                <div class="user-forms-border" id="alert_info">
                    <p>If you are a wholesaler or want to become our retailer, please fill out this form and we'll reply the wholesale pricelist as soon as possible.</p>
                </div>
	        <div class="user-forms-border">
	        	<div id="message" style="display:none">
	        		<p>Thanks for your interest in Cheap-Lingerie.com!<p>
	        		<p>If you are a wholesaler customer or want to become our retailer, please visit our wholesale price website:<a style="color:#f00;font-size: 14px;font-weight: bold;margin: 0px 5px;text-decoration: underline;" href="http://www.iwantlingerie.com/">http://www.iwantlingerie.com/</a>.For any other questions, please contact support@cheap-lingerie.com. Thank you!</p>
	        	</div>
	            <form method="post">
					<div class="login_content">
		            	<div class="name">
		                    <span>Name:</span><br />
		                    <input type="text" value="" name="name"  class="elmbBlur"/>*
		                </div>
		                <div class="passwd">
		                	<span>Email:</span> <br />
		                    <input value="" name="email" class="elmbBlur"/>*
		                </div>
		                <div class="passwd">
		                	<span>Country:</span> <br />
		                    <input value="" name="country" class="elmbBlur"/>*
		                </div>
		                <div class="passwd">
		                	<span>Phone Number:</span> <br />
		                    <input value="" name="phone" class="elmbBlur"/>*
		                </div>
		                <div class="passwd">
		                	<span>Website:</span> <br />
		                    <input value="" name="website" class="elmbBlur"/>
		                </div>
                                <div class="passwd">
		                	<span>Comments:</span> <br />
		                    <textarea name="comment" style="border:1px solid #D9D9D9;width:200px;height:100px;color:#666;"></textarea>
		                </div>
	                </div>
	            </form>
	            <div>
			        <div class="login-submit">
			        	<input id="confirm-btn" type="button" class="confirm" value="Confirm"/>
			            <input id="cancel-btn" type="button" class="cancel" value="Close"/>
			        </div>
		        </div>
	        </div>
	    </div>
</div>