<div id="shared_info_dialog">
	<div style="text-align: center;width: 500px;">
		<h1 style="font-size: 26px;color: black;margin:25px 0 5px 0">Thank you for your sharing!</h1>
		<p style="font-size: 17px;font-weight: bolder;color: #E55D4E;margin-bottom:30px;">A 20% discount has been applied to all products.
		<a href="#" class="close_btn"><img src="<?php echo themeResourceURI('images/cha.png');?>"/></a>
	</div>
</div>